###############################################################################
#                                    VTCOL
###############################################################################

[package]
name    = "vtcol"
version = "0.42.0"
authors = [ "Philipp Gesang <phg@phi-gamma.net>" ]

[[bin]]
name = "vtcol"
test = false
doc  = false

